name: "Building, Pushing, and Testing Raphee Beauty Docker Images"
on:
    push:
        branches:
            - master
            - dev
            - qa
            - prod
    pull_request:
        branches:
            - master
            - dev
            - qa
            - prod
jobs:
    check-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Check branch name
              run: |
                if [[ "${{ github.event_name }}" == "pull_request" && ("${{ github.event.pull_request.base.ref }}" != "dev" && "${{ github.event.pull_request.base.ref }}" != "prod" && "${{ github.event.pull_request.base.ref }}" != "qa") ]]; then
                    echo "Invalid merge destination. Please merge into dev, prod, or qa only."
                    exit 1
                fi
    sonaqube-scan:
        runs-on: ubuntu-latest
        permissions: read-all
        needs: check-branch
        steps:
            - name: Check out code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}